
logging:
  level:
    org.springframework: ERROR
    com.assignment.processor: INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d %p %c{1.} [%t] %m%n"
  file: dataServer.log

spring:
  profiles:
    active: dev